CREATE DATABASE BD2020_AULA09

USE BD2020_AULA09

CREATE TABLE MARCA(
	ID_MARCA INT IDENTITY NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	DESCRICAO VARCHAR(150),
	DATA_FUNDACAO DATE NOT NULL,

	CONSTRAINT PK_ID_MARCA PRIMARY KEY (ID_MARCA)
)

CREATE TABLE PROPRIETARIO(
	ID_PROPRIETARIO INT IDENTITY NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	ENDERECO VARCHAR(250) NOT NULL,
	BAIRRO VARCHAR(250) NOT NULL,
	CIDADE VARCHAR(200) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
	RENDA_MENSAL DECIMAL(18,2),

	CONSTRAINT PK_ID_PROPRIETARIO PRIMARY KEY (ID_PROPRIETARIO)
)

CREATE TABLE VEICULO(
	ID_VEICULO INT IDENTITY NOT NULL,
	PLACA VARCHAR(20) NOT NULL,
	ANO_FABRICACAO DATE NOT NULL,
	ID_MARCA INT NOT NULL,
	ID_PROPRIETARIO INT,
	VALOR DECIMAL(18,2) NOT NULL,
	DATA_COMPRA DATETIME NOT NULL,

	CONSTRAINT PK_ID_VEICULO PRIMARY KEY(ID_VEICULO),
	CONSTRAINT FK_ID_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA (ID_MARCA),
	CONSTRAINT FK_ID_PROPRIETARIO FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIO (ID_PROPRIETARIO)

)


--1. Exibir a quantidade de Marcas cadastradas.
SELECT COUNT(*) AS MARCAS_CADASTRADAS FROM MARCA

--2. Exibir a soma dos valores (valor) de todos os Veículos.
SELECT SUM(VALOR) AS SOMA_VALORES
FROM VEICULO

--3. Exibir a média de Renda Mensal dos proprietários que nasceram entre 1980 e 2000.
SELECT AVG(RENDA_MENSAL) AS RENDA_MENSAL
FROM PROPRIETARIO
WHERE YEAR(DATA_NASCIMENTO) BETWEEN 1980 AND 2000

--4. Exibir a quantidade de Veículos agrupados por Ano de Fabricação.
SELECT COUNT(*) AS VEICULOS_FABRICADOS, ANO_FABRICACAO
FROM VEICULO
GROUP BY ANO_FABRICACAO

--5. Exibir a renda mensal média dos proprietários agrupadas por cidade.
SELECT AVG(RENDA_MENSAL) AS RENDA_MENSAL, CIDADE
FROM PROPRIETARIO
GROUP BY CIDADE

--6. Exibir a soma dos valores dos veículos agrupados por ano de fabricação.
SELECT SUM(VALOR) AS SOMA_VALORES, ANO_FABRICACAO
FROM VEICULO
GROUP BY ANO_FABRICACAO

--7. Exibir por ano e mês de compra (DataCompra) o veículo mais barato e o veículo mais caro.
SELECT MIN(VALOR) AS VEICULO_BARATO, MAX(VALOR) AS VEICULO_CARO, YEAR(DATA_COMPRA) AS ANO_COMPRA, MONTH(DATA_COMPRA) AS MES_COMPRA
FROM VEICULO
GROUP BY DATA_COMPRA

--8. Exibir a quantidade de proprietários agrupados por cidade. Somente devem ser exibidas a cidades com 3 ou mais proprietários.
SELECT COUNT(*) AS QUANTIDADE_PROPRIETARIOS, CIDADE
FROM PROPRIETARIO
GROUP BY CIDADE
HAVING COUNT(*) >= 3

--9. Exibir a quantidade de veículos comprados por mês (DataCompra) quando o valor do veículo for superior a R$ 30.000,00. 
--Além disso, somente devem ser exibidos os meses com menos de 5 veículos vendidos.
SELECT COUNT(*) AS QUANTIDADE_COMPRADOS, MONTH(DATA_COMPRA) AS MES_COMPRA
FROM VEICULO
WHERE VALOR >= 30000
GROUP BY MONTH(DATA_COMPRA)
HAVING COUNT(*) < 5


--10. Exibir a renda mensal média dos proprietários agrupadas por cidade. Somente as cidades com rente entre R$ 5.000,00 e R$ 10.000,00 devem ser exibidas.
SELECT AVG(RENDA_MENSAL) AS RENDA_MEDIA, CIDADE
FROM PROPRIETARIO
GROUP BY CIDADE
HAVING AVG(RENDA_MENSAL) BETWEEN 5000 AND 10000

--11. Exibir a soma dos valores dos veículos agrupados por ano de fabricação. Somente os anos com soma inferior a R$ 25.000,00 devem ser exibidos.
SELECT SUM(VALOR) AS SOMA_VALORES, YEAR(ANO_FABRICACAO) AS ANO_FABRICACAO
FROM VEICULO
GROUP BY YEAR(ANO_FABRICACAO)
HAVING SUM(VALOR) < 25000
